Repository jet-dev-team/drupal-dockerizer, pull requests merged in 2021-04, with the labels that each got.

#28 Rename config.yml to dockerizer.yml
  .github/workflows/basic_test.yml
  db.yml
  drush-commands.yml
  main.yml
  reset.yml
  stop.yml
  up.yml
Labels: invalid

#31 Implement test for ssl functionality
  .github/workflows/ssl_test.yml
Labels: testing

#41 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#36 Improve README.md
  README.md
Labels: documentation

#52 Add preflight checks
  main.yml
  tasks/preflight.yml
  tasks/preflight/docker-group.yml
  tasks/preflight/end_play.yml
Labels: enhancement

#53 Change network settings logic
  .github/workflows/test_basic.yml
  .github/workflows/test_db_import.yml
  .github/workflows/test_memcache.yml
  .github/workflows/test_multiple_env.yml
  .github/workflows/test_ssl.yml
  .gitignore
  README.md
  default.config.yml
  main.yml
  reset.yml
  stop.yml
  tasks/advanced-networking-setup.yml
  tasks/docker-up.yml
  tasks/local-hosts-setup.yml
  tasks/preflight.yml
  tasks/preflight/network.yml
  templates/apache.conf.j2
  templates/docker-compose.yml.j2
Labels: wontfix
